name: Build Unity Android

on:
  push:
    branches: [PipelineCICD]
  pull_request:
    branches: [PipelineCICD]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode keystore from secret
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android.keystore

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          buildName: MyGameBuild
          customParameters: >
            --android-keystore-path ./android.keystore
            --android-keystore-password ${{ secrets.KEYSTORE_PASSWORD }}
            --android-keyalias ${{ secrets.KEY_ALIAS }}
            --android-keyalias-password ${{ secrets.KEY_ALIAS_PASSWORD }}
          unityVersion: auto
          versioning: Semantic
          androidExportType: androidPackage
          androidSymbolType: none
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/Android/*.apk
